name: ashuothshh job
'on':
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - terraform.tfstate
jobs:
  infra-provision-job:
    runs-on: ubuntu-latest
    steps:
      - name: taking code from my repo
        uses: actions/checkout@v5
        with:
          ref: main
      - name: installing terraform
        uses: hashicorp/setup-terraform@v3
      - name: my first step to test github action
        run: |
          echo "Hello world"
          git version 
          whoami
          ls -a 
          terraform version
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-southeast-2
      - name: verify aws connection
        run: |
          echo "checking with commond"
          aws s3 ls
      - name: deploy terraform resources
        run: |
          echo "implementing terraform deals"
          terraform init 
          terraform plan
          sleep 2
          terraform apply --auto-approve
          ls modules/ec2
      - name: uploading ansible inventory to github artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ashutoshh-github-artifact
          path: |
           modules/ec2/ansible-inventory.txt
           modules/ec2/vijay-key.pem
  infra-c-job:
    needs: infra-provision-job
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v5
        with:
          ref: main
      - name: login to aws creds
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: ap-southeast-2
      - name: downloading ansible inventory from artifact
        uses: actions/download-artifact@v5
        with:
          name: ashutoshh-github-artifact
      - name: Display structure of downloaded files
        run: ls -R

      - name: Installing ansible
        run: |
         echo "setup ansbilble in ubuntu machine"
         sudo apt update
         sudo apt install ansible -y
         ansible --version
         
      - name: running ansible playbook in dynamic inventory
        run: |
          echo "Running ansible playbook"
          chmod 400 ashutoshh-key.pem
          cd my-ansible
          ansible-playbook -i ../ansible-inventory.txt --private-key ../vijay-key.pem playbook

      - name: installing terraform
        uses: hashicorp/setup-terraform@v3
      - name: destroying it
        run: |
          echo "checking resoruces"
          terraform init 
          terraform state list
          terraform destroy --auto-approve
     

      
      
      
      
      